import '../audio/audio_controller.dart';
import '../audio/sounds.dart';

/// Named sound cues for the games.
///
/// Games ask for a *feeling* (`pop`, `celebrate`, `wobble`) rather than an
/// asset path, so swapping the actual audio later is a one-file change here.
///
/// Everything routes through the template's [AudioController], which already
/// honours the mute settings — so muting in the parent area silences these
/// automatically and no game has to check.
///
/// The audio itself is soft synthesised placeholder tone, generated by
/// `tools/make_sfx.py` and tuned to the kid rules: nothing percussive, nothing
/// that bangs, nothing that reads as a buzzer. Real recorded audio replaces the
/// files in `assets/sfx/` without touching this file.
class KidSounds {
  const KidSounds(this._audio);

  final AudioController _audio;

  /// A balloon popped, a shape dropped in the right hole — the small, frequent
  /// "yes that worked" cue.
  ///
  /// A gentle rising "boop", NOT a realistic balloon bang: a burst startles a
  /// five-year-old, and this plays many times a minute.
  ///
  /// [progress] (0..1) is how far the child is through the current set. The cue
  /// climbs the pop samples in order as it rises, so the sound itself says
  /// "nearly there" and the celebration lands as the resolution of a phrase
  /// rather than an unrelated noise. A child who cannot read a progress bar
  /// hears this immediately — it is the same trick as a coin ladder.
  ///
  /// The rungs are the ascending `kid_pop*` samples, so a deeper ladder is
  /// purely a matter of adding more of them (`tools/make_sfx.py`): nothing here
  /// assumes how many there are.
  void pop({double progress = 0}) =>
      _audio.playSfx(SfxType.kidPop, variant: popRung(progress));

  /// The rung [pop] would play at [progress]. Exposed for tests, which cannot
  /// hear the ladder climb.
  static int popRung(double progress) {
    final rungs = soundTypeToFilename(SfxType.kidPop).length;
    return (progress.clamp(0.0, 1.0) * (rungs - 1)).round();
  }

  /// The big one, after a set of successes. Deliberately longer, louder and
  /// more musical than [pop] — with no score and no winning, this is the
  /// reward (CLAUDE.md §3).
  void celebrate() => _audio.playSfx(SfxType.kidCelebrate);

  /// A gentle "not that one, try again". Deliberately soft and short: this is
  /// the only cue that follows a mistake, and it must never sound like a
  /// buzzer. Never accompanied by anything that takes progress away.
  void wobble() => _audio.playSfx(SfxType.kidWobble);

  /// A button or menu tap.
  void tap() => _audio.playSfx(SfxType.kidTap);
}
