import 'dart:math';

import '../audio/audio_controller.dart';
import '../audio/sounds.dart';

/// Named sound cues for the games.
///
/// Games ask for a *feeling* (`pop`, `celebrate`, `wobble`) rather than an
/// asset path, so swapping the actual audio later is a one-file change here.
///
/// Everything routes through the template's [AudioController], which already
/// honours the mute settings — so muting in the parent area silences these
/// automatically and no game has to check.
///
/// The audio itself is soft synthesised placeholder tone, generated by
/// `tools/make_sfx.py` and tuned to the kid rules: nothing percussive, nothing
/// that bangs, nothing that reads as a buzzer. Real recorded audio replaces the
/// files in `assets/sfx/` without touching this file.
class KidSounds {
  const KidSounds(this._audio);

  final AudioController _audio;

  /// A balloon popped, a shape dropped in the right hole — the small, frequent
  /// "yes that worked" cue.
  ///
  /// A gentle rising "boop", NOT a realistic balloon bang: a burst startles a
  /// five-year-old, and this plays many times a minute.
  ///
  /// [progress] (0..1) is how far the child is through the current set. The cue
  /// climbs the pop samples in order as it rises, so the sound itself says
  /// "nearly there" and the celebration lands as the resolution of a phrase
  /// rather than an unrelated noise. A child who cannot read a progress bar
  /// hears this immediately — it is the same trick as a coin ladder.
  ///
  /// The rungs are the ascending `kid_pop*` samples, so a deeper ladder is
  /// purely a matter of adding more of them (`tools/make_sfx.py`): nothing here
  /// assumes how many there are.
  void pop({double progress = 0}) =>
      _audio.playSfx(SfxType.kidPop, variant: popRung(progress));

  /// The rung [pop] would play at [progress]. Exposed for tests, which cannot
  /// hear the ladder climb.
  static int popRung(double progress) {
    final rungs = soundTypeToFilename(SfxType.kidPop).length;
    return (progress.clamp(0.0, 1.0) * (rungs - 1)).round();
  }

  /// The big one, after a set of successes. Deliberately longer, louder and
  /// more musical than [pop] — with no score and no winning, this is the
  /// reward (CLAUDE.md §3).
  void celebrate() => _audio.playSfx(SfxType.kidCelebrate);

  /// A gentle "not that one, try again". Deliberately soft and short: this is
  /// the only cue that follows a mistake, and it must never sound like a
  /// buzzer. Never accompanied by anything that takes progress away.
  void wobble() => _audio.playSfx(SfxType.kidWobble);

  /// A button or menu tap.
  void tap() => _audio.playSfx(SfxType.kidTap);

  /// One number of a countdown (Blast Off).
  ///
  /// [secondsLeft] is what is being counted *to*, and [rungs] how many rungs
  /// the ladder should be spread over — normally 10, whatever the countdown's
  /// real length, so a five-minute tidy-up climbs the same phrase as a
  /// ten-second blast off and resolves into the launch the same way.
  ///
  /// This is the one cue that is deliberately *anticipatory*: it is not
  /// feedback for something the child did, it is the sound of something
  /// arriving. Nothing about it may read as urgency — no ticking, no
  /// heartbeat, no siren (CLAUDE.md §3).
  ///
  /// TODO(audio): this stands in for a recorded VOICE saying the number, which
  /// is the real feature — a child who cannot read can absolutely count, and
  /// counting along out loud is the whole activity. The tone plays under the
  /// voice once it exists; see `lib/games/blast_off/assets.dart`.
  void count(int secondsLeft, {int rungs = 10}) =>
      _audio.playSfx(SfxType.kidCount, variant: countRung(secondsLeft, rungs));

  /// The rung [count] would play. Exposed for tests, which cannot hear it.
  ///
  /// Rung 0 is the furthest away and the last rung is "one", so the phrase
  /// always resolves upward into [launch].
  static int countRung(int secondsLeft, int rungs) {
    final ladder = soundTypeToFilename(SfxType.kidCount).length;
    final highest = min(ladder, rungs) - 1;
    // Everything above the ladder's reach sits on its bottom rung, so a long
    // countdown is simply quiet for a while and then starts climbing.
    final fromEnd = secondsLeft - 1;
    return (highest - fromEnd).clamp(0, ladder - 1);
  }

  /// Zero. The rocket goes. Pairs with [celebrate] rather than replacing it.
  void launch() => _audio.playSfx(SfxType.kidLaunch);

  /// The horn (Car Trip). The only cue in the app that is not feedback for
  /// anything: it answers a button that does nothing to the game, and that is
  /// the whole point of it.
  ///
  /// [press] is how many times the horn has been pressed, so repeated honks
  /// alternate between the variants instead of repeating one sample — a child
  /// who has just found this button presses it twenty times.
  void horn({int press = 0}) => _audio.playSfx(SfxType.kidHorn, variant: press);
}
