/// Every asset path Car Trip uses, in one place.
///
/// Placeholder art is drawn in code (coloured shapes), so there are no image
/// paths yet. When real artwork arrives the paths land here and nothing else in
/// the game changes — see CLAUDE.md §5.
class CarTripAssets {
  const CarTripAssets._();

  // TODO(art): the car, seen from behind. Currently shape-drawn in
  // `components/car.dart`. Whatever replaces it must keep the same drawn width
  // in road units (`Car.drawWidth`), or the generous collision width
  // (`Car.halfWidth`) stops matching what the child sees.
  // static const car = 'images/car_trip/car.png';

  // TODO(art): the things on the road — cone, beach ball, hay bale, bin,
  // puddle, leaves, mud, rainbow arch, car wash. One sprite each; the sizes and
  // the reaches live in `road.dart` and are deliberately not the same number,
  // so swapping art does not change how generous the game is.
  // static const cone = 'images/car_trip/cone.png';

  // TODO(art): the passengers and the field animals — dog, duck, sheep, bear,
  // cow, tractor, tree.
  // static const dog = 'images/car_trip/dog.png';

  // The horn cue is a shared kid sound (`KidSounds.horn`), generated by
  // `tools/make_sfx.py` like the rest of them — not a per-game asset.
}
