/// Every asset path Neil the Seal uses, in one place.
///
/// Placeholder art is drawn in code (coloured shapes), so there are no image
/// paths yet. When real artwork arrives the paths land here and nothing else in
/// the game changes — see CLAUDE.md §5.
class NeilAssets {
  const NeilAssets._();

  // TODO(art): Neil himself. Currently shape-drawn in
  // `components/neil_painter.dart`. Whatever replaces him must keep the same
  // drawn size in town units (`NeilPainter.bodyWidth`/`bodyHeight`) and the
  // same rub target (`NeilPainter.rubReach`), or the one hand-sized thing in
  // this game stops matching what the child sees.
  //
  // He is also the obvious candidate for the shared Rive character
  // (`lib/shared/rive_character.dart`): the galumph, the flop, the wriggle and
  // the yawn are exactly the sort of thing a state machine is for. The scope's
  // open question — whether an animal this specific belongs in `shared/` at all
  // — is still open, so nothing is wired to Rive yet.
  // static const neil = 'images/neil_the_seal/neil.png';

  // TODO(art): the props. One sprite each: car, cone, jetty, kelp, bin, hose,
  // trampoline, sand, boat. The sizes AND the reaches live in `town.dart` and
  // are deliberately not the same number, so swapping art cannot quietly
  // change how generous the game is.
  // static const car = 'images/neil_the_seal/car.png';

  // TODO(art): the town watching — seagull, wallaby, pademelon, wombat, dog,
  // kid on a bike, ute, cow, shack.
  // static const wallaby = 'images/neil_the_seal/wallaby.png';

  // The sounds are shared kid cues (`KidSounds.flump`, `boing`, `squelch`,
  // `bellow`, `answer`, `wriggle`, `snore`), generated by `tools/make_sfx.py`
  // like the rest of them — not per-game assets. They are placeholders too:
  // real recordings drop into `assets/sfx/` under the same names with no Dart
  // change at all.
}
